export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const GET_MESSAGE = "GET_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
